### ISSUE TITLE
Issue with OpenMM-torch installation with NNPOps and TorchANI

### ISSUE THREAD

**Issue by rvkrishnan30** [openmm/openmm-torch#76]
Hi, 

Following the [example ](https://github.com/openmm/openmm-torch/blob/master/tutorials/openmm-torch-nnpops.ipynb), I installed the required packages openmm-torch, TorchAni and NNPOps with the command

`conda create -n tmp-test -q -c conda-forge openmm-torch nnpops torchani openmmtools  cudatoolkit=11.3`

Importing torchani throws "`undefined symbol`" ImportError: 

>>> import torch as pt
>>> from torchani.models import ANI2x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/venkat/miniconda3/envs/tmp-test/lib/python3.9/site-packages/torchani/__init__.py", line 34, in <module>
    from .aev import AEVComputer
  File "/home/venkat/miniconda3/envs/tmp-test/lib/python3.9/site-packages/torchani/aev.py", line 14, in <module>
    from . import cuaev  # type: ignore # noqa: F401
ImportError: /home/venkat/miniconda3/envs/tmp-test/lib/python3.9/site-packages/torchani/cuaev.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKS0_PSo
>>>

Am I right that this is likely due to the different versions of pytorch these dependencies are built with? NNPOps and TorchANI have both been upgraded to work with PyTorch1.11 but openmm-torch seems to be with PyTorch 1.10 and pytorch-gpu-1.10. The above conda environment (`tmp-test`) has PyTorch1.10 and this makes it incompatible with torchANI and NNPOps and thus returns `undefined symbol` error when I attempt to import either of these packages. Any idea on how I can solve this and make all these work together?

These are some related topics I found useful: https://github.com/openmm/NNPOps/issues/54, https://github.com/conda-forge/openmm-torch-feedstock/issues/16, https://github.com/conda-forge/openmm-torch-feedstock/pull/17, https://github.com/openmm/openmmexampleplugin/issues/19. 

I also tried compiling OpenMM 7.7 and OpenMM-torch from source but not much luck either. I did manage to get OpenMM installed, but then installing openmm-torch gave this following error: 

`conda create -n py39-nnpops -c conda-forge nnpops python=3.9`

(py39-nnpops) venkat@ws:/home/venkat/testing/openmm-torch/build$ make install
Consolidate compiler generated dependencies of target OpenMMTorch
[ 16%] Built target OpenMMTorch
[ 30%] Built target CopyTestFiles
Consolidate compiler generated dependencies of target TestSerializeTorchForce
[ 33%] Linking CXX executable ../../TestSerializeTorchForce
/usr/bin/ld: ../../libOpenMMTorch.so: undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ../../libOpenMMTorch.so: undefined reference to `torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>)'
collect2: error: ld returned 1 exit status
make[2]: *** [serialization/tests/CMakeFiles/TestSerializeTorchForce.dir/build.make:112: TestSerializeTorchForce] Error 1
make[1]: *** [CMakeFiles/Makefile2:259: serialization/tests/CMakeFiles/TestSerializeTorchForce.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

I am not sure if this is related to https://github.com/openmm/openmmexampleplugin/issues/19, where @peastman refers to `ABI inconsistency`. I changed the flag "-D_GLIBCXX_USE_CXX11_ABI=0" to "-D_GLIBCXX_USE_CXX11_ABI=1" in my TorchConfig.cmake (libtorch/share/cmake/Torch/TorchConfig.cmake) hoping that would solve the installation issue but in vain. 

Could you please help me with this. I'll be happy to provide any additional information if needed to reproduce this error. I am working on a Linux (Debian) workstation and with python 3.9.

**Comment by raimis** [comment]
@rvkrishnan30 OpenMM-Torch 0.7 has been released and the packages are available on `conda-forge`. Could you confirm that it solves the issue?

**Comment by rvkrishnan30** [comment]
@raimis, it all looks good now without any import issues. Thank you very much
