### ISSUE TITLE
Issues with undefined references when building tests

### ISSUE THREAD

**Issue by ndtrung81** [openmm/openmm-torch#171]
I am building openmm-torch from source in an activated enviroment with torch 2.8 and OpenMM 8.3.1 installed. The OpenMM installation was successfully as I ran `python -m openmm.testInstallation`. I can run the apo1 example on a GPU with the OpenCL backend. 

However, the cmake build of openmm-torch after generating the 4 targets `libOpenMMTorch.so`, `libOpenMMTorchOpenCL.so`, `libOpenMMTorchCUDA.so` and `libOpenMMTorchReference.so` failed at the test targets with undefined refrence to functions in `torch::jit` and `c10`:

``` [62%] Linking CXX executable ../../TestSerializeTorchForce
cd /home/ndtrung/Codes/openmm/openmm-torch/build/serialization/tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/TestSerializeTorchForce.dir/link.txt --verbose=1
/usr/bin/c++ -D_GLIBCXX_USE_CXX11_ABI=0 CMakeFiles/TestSerializeTorchForce.dir/TestSerializeTorchForce.cpp.o -o ../../TestSerializeTorchForce   -L/home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/OpenMM.libs/lib  -L/home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/OpenMM.libs/lib/plugins  -L/lib/intel64  -L/lib/intel64_win  -L/lib/win-x64  -Wl,-rpath,/home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/OpenMM.libs/lib:/home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/OpenMM.libs/lib/plugins:/lib/intel64:/lib/intel64_win:/lib/win-x64:/home/ndtrung/Codes/openmm/openmm-torch/build:/home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/torch/lib:/usr/local/cuda-12.5/lib64 ../../libOpenMMTorch.so -lOpenMM /home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/torch/lib/libtorch.so -Wl,--no-as-needed,"/home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so" -Wl,--as-needed -Wl,--no-as-needed,"/home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so" -Wl,--as-needed /home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/torch/lib/libc10_cuda.so /home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/torch/lib/libc10.so /usr/local/cuda-12.5/lib64/libcudart.so -Wl,--no-as-needed,"/home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/torch/lib/libtorch.so" -Wl,--as-needed /home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/torch/lib/libc10.so /usr/local/cuda-12.5/lib64/libnvrtc.so /home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/torch/lib/libc10_cuda.so 
/usr/bin/ld: CMakeFiles/TestSerializeTorchForce.dir/TestSerializeTorchForce.cpp.o: in function `serializeAndDeserialize(TorchPlugin::TorchForce)':
TestSerializeTorchForce.cpp:(.text+0x49c): undefined reference to `torch::jit::Module::save(std::ostream&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&) const'
/usr/bin/ld: TestSerializeTorchForce.cpp:(.text+0x512): undefined reference to `torch::jit::Module::save(std::ostream&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&) const'
/usr/bin/ld: CMakeFiles/TestSerializeTorchForce.dir/TestSerializeTorchForce.cpp.o: in function `testSerializationFromModule()':
TestSerializeTorchForce.cpp:(.text+0x1643): undefined reference to `torch::jit::load(std::string const&, std::optional<c10::Device>, bool)'
/usr/bin/ld: CMakeFiles/TestSerializeTorchForce.dir/TestSerializeTorchForce.cpp.o: in function `c10::intrusive_ptr_target::~intrusive_ptr_target()':
TestSerializeTorchForce.cpp:(.text._ZN3c1020intrusive_ptr_targetD2Ev[_ZN3c1020intrusive_ptr_targetD5Ev]+0x1e4): undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::string const&)'
...
```
I am working on a Debian 12 box, with CUDA 12.2 and GCC 12.2. The cmake command to configure the build:
```
mkdir build
cd build
cmake ../ -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" -DCMAKE_INSTALL_PREFIX=/home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/ -DOPENMM_DIR=/home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/OpenMM.libs -DPYTORCH_DIR=/home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages/ -DOPENCL_LIBRARY=/usr/local/cuda-12.5/lib64/libOpenCL.so
```
I thought of skipping building the tests, but if the test builds failed, it would be likely that the installation would fail at runtime as well.

Any suggestion to resolve this will be appreciated.

Thanks,
-Trung

**Comment by peastman** [comment]
That looks like an ABI incompatibility.  Did you also build OpenMM from source, or did you install a precompiled package?  If the latter, did you install it with pip or conda?  And how did you install Pytorch?

All packages that you want to link together need to use the same ABI.  That includes Pytorch, OpenMM, and OpenMM-Torch.  Conda packages generally use the C++11 ABI, while pip packages generally use the older ABI.  You're telling it to use the old ABI with `-D_GLIBCXX_USE_CXX11_ABI=0`, but I think you're using a Pytorch package compiled with the new ABI.

**Comment by ndtrung81** [comment]
Thanks for the suggestion with the ABI incompatibility.  I installed PyTorch (pip install torch torchaudio torchaudio) and OpenMM (`pip install openmm[cuda12]`) as in the doc pages. The environment was created via `python3 -m venv`. The package info are shown as below. The command `python -c "import torch; print(torch.cuda.is_available())"` returns True in the enviroment on my machine.

The reason I used `-D_GLIBCXX_USE_CXX11_ABI=0`  is to avoid the ABI incompatibility issues with other functions such as `OpenMM::SerializationNode::setName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`. 

I will try to build both PyTorch and OpenMM from source then.


```
pip show torch
Name: torch
Version: 2.8.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-cufile-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: torchaudio, torchvision
(openmm-env) ndtrung:openmm $ pip show OpenMM
Name: OpenMM
Version: 8.3.1
Summary: Python wrapper for OpenMM (a C++ MD package)
Home-page: https://openmm.org
Author: Peter Eastman
Author-email: 
License: Python Software Foundation License (BSD-like)
Location: /home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages
Requires: numpy
Required-by: dmff
(openmm-env) ndtrung:openmm $ pip show OpenMM-CUDA-12
Name: OpenMM-CUDA-12
Version: 8.3.1
Summary: CUDA platform for OpenMM
Home-page: https://openmm.org
Author: Peter Eastman
Author-email: 
License: 
Location: /home/ndtrung/Codes/openmm/openmm-env/lib/python3.11/site-packages
Requires: nvidia-cuda-cupti-cu12, nvidia-cuda-nvcc-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cufft-cu12
Required-by: 

```

**Comment by ndtrung81** [comment]
Installing PyTorch turns out to be a tall order, and the build failed on me with more convoluted issues with its dependencies than what I am having with the OpenMM-Torch build here. 

My goal is to have a full functional stack: Python, OpenMM, PyTorch and OpenMM-Torch with CUDA and OpenCL backends. The first 3 can be installed straightforwardly as adverstised. For openmm-torch, I tried installing with conda (`conda install -c conda-forge openmm-torch`) but only got the CPU version (connda-forge/linux-64::openmm-torch-1.5.1-cpu_py313hd787a1b_0). I suppose this is because there is no cuda version available for python 3.13.  

I did some Google search and ChatGPT, and the suggestions are to try older versions: python 3.9, cudatoolkit 11, openmm 8.1 and openmm-torch 1.4.

What is the recommended way to get the most up-to-date version of OpenMM and OpenMM-Torch with CUDA/OpenCL backends? Thanks!

**Comment by peastman** [comment]
There's a CUDA build for Python 3.13.  You can find the list of packages at https://anaconda.org/conda-forge/openmm-torch/files?version=1.5.1.  It includes `linux-64/openmm-torch-1.5.1-cuda126py313ha8b2f1a_0.conda`.

If it's installing the CPU build, that suggests conda thinks you don't have CUDA.  Are you installing it on a computer with a CUDA driver?  This can come up, for example, if you're installing it on the login node of a cluster, but only the compute nodes have GPUs, not the login node.

**Comment by ndtrung81** [comment]
Thanks very much for pointing out the list of available versions and the version that is suitable for my environment. I can now install the version I wanted. You are correct, I was trying to conda install it on a login node which doesn't have a CUDA driver installed. The compute nodes don't have internet access though. Installing a specific package on the login node is sufficient for my work. 

I will revisit the issue with incompatible ABI for building openmm-torch from source later. Thanks again for your help.

**Comment by peastman** [comment]
Glad that worked!
